language: python
before_install:
  - sudo apt-get install -y devscripts
script:
  - export SCM_REV=$TRAVIS_COMMIT
  - export SCM_REV=`git rev-parse --short HEAD`
  - export VERSION=`make versioninfo -s`
  - export RELEASE_DIR=`echo release_\`date +"%Y_%m_%d"\``
  - make compile
  - make package
after_success:  
  - curl -X PUT -u travis-ci:travis-ci "http://owncloud.sg-dev.de/remote.php/webdav/PFS/photofilmstrip_$VERSION-1_all.deb" --data-binary @"$RELEASE_DIR/photofilmstrip_$VERSION-1_all.deb"